spring.datasource.url=jdbc:postgresql://dpg-d6taj1ia214c73cf1tg0-a:5432/url_dliy
spring.datasource.username=url_dliy_user
spring.datasource.password=CCImNDxyb37mYTHp49Xqpk1jaCJu90EQ

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}